### ISSUE TITLE
Make module configurable

### ISSUE THREAD

**Issue by TheComamba** [TheComamba/UnKenny#19]
This might be especially interesting if we want to support several languages.

**Comment by TheComamba** [comment]
Yes, we can. Although it is not large.

**Comment by TheComamba** [comment]
I think we should offer the user choice of
* The used language model
* The min and max number of tokens
* The prompt framing

**Comment by Armandeus66** [comment]
If there were an option to send to chat using "/talk" we could integrate this with Talking Actors, which allows us to assign a token in a scene with an AI voice from an Elevenlabs subscription API.
https://github.com/acd-jake/acd-talking-actors

**Comment by TheComamba** [comment]
@Armandeus66 And all we'd have to do is offer the option to add a /talk at the beginning of the reply, correct? That sounds brilliant! Thanks for the input.

**Comment by TheComamba** [comment]
@Armandeus66 I implemented the functionality with version 0.1.2. Could you verify that it works as expected? I do not have an Elevenlabs subscription. 🙂

**Comment by Armandeus66** [comment]
Hi! Thanks for being interested in this!
I got the Unkenny portion of this to work (using the first chat model in the list), although it froze my browser for about 15 seconds. However, the "/talk" was output as part of the chat message (meaning you could see it in the text), not as a chat command, and so the integration with Talking Actors was unsuccessful.
Also, there were what appeared to be some character code problems. The first two characters of "I'm" were switched to Chinese characters. Another thing is that it appended text emoji such as :)) which would affect what the Elevenlabs might say.
I could try again if you update the macro to send "/talk" as a chat command, and not part of the chat text. The cheapest Elevenlabs subscription that also gives you an API key is $5 a month, so it might be faster to join so you can do testing without having to make sure exactly what I am doing right or wrong.

**Comment by TheComamba** [comment]
Thanks for the report!

Yeah, the first model is a bit of a weirdo. I can confirm that it takes somewhat longer to generate Tokens, and they often contain non-Ascii characters and bizarre content. Good thing the model is configurable now.^^

I have the growing suspicion that the way I generate the chat messages somehow bypasses the text macro handling of foundry. I will investigate.

But the model is configurable now, so I will track this in the new issue #27.
