### ISSUE TITLE
Macros are no longer added automatically when making an actor unkenny.

### ISSUE THREAD

**Issue by TheComamba** [TheComamba/UnKenny#22]

**Comment by TheComamba** [comment]
This was never truly the case, I just didn't find them...

**Comment by AX8VR** [comment]
Hello, I have the same issue. If it's being created as a Macro, I do not see where. It's not in the compendium tab anywhere. On the latest version of FVTT and dnd 5e

**Comment by TheComamba** [comment]
Just left of the macro hotbar is a folder symbol, and if you click on it, the macro should be listed. From there you can drag it into the hotbar. I always have to look for that folder symbol when I haven't accessed it in a while...
