### ISSUE TITLE
The /talk text macro is not evaluated in LLM Output

### ISSUE THREAD

**Issue by TheComamba** [TheComamba/UnKenny#27]

**Comment by TheComamba** [comment]
ChatMessage.create lives on the same layer as the chatMessage Hook. During normal execution via the ChatLog both are called by the processMessage function, which also handles the predefined chat macros like /roll. Sadly, processMessage is apparently not callable from a module. The simple solution is to call the chatMessage hook, checking the output to see if the message was already posted by one of the hooked functions, and then posting it ourselves if that is not the case:
https://github.com/TheComamba/UnKenny/blob/main/src/scripts/shared.js
This has the obvious disadvantage of code duplication and the less obvious disadvantage that the predefined chat macros will not be recognised. So be it for the moment.
@Armandeus66 The integration with Talking Actors seemed to work on my end, my debugger took me to the talkingactors.connector.processChatMessage function, and I got to the point where the module complained that there is no voice selected. If you would verify one final time I could close this bug. :)

**Comment by Armandeus66** [comment]
Thanks for working on this!
I checked that Talking Actors worked, set up your module with a test actor and tried it out (I wrote the details of this in my previous post.)
In the macro, I asked, "Please introduce yourself." It worked!
"Talked Text:" was displayed before the AI's answer, but that was not read by the Elevenlabs voice, so it wasn't a problem.
The Felladrin AI responded: "I am Nona, and this characters page explains some facts about myself。 I also have fun playing games with people in my group. :))"
The voice did not have trouble with the Japanese period character, but it said something like "sahtee" when it got to the smiley-thing at the end. It would be a bonus if the AI would stop doing that.
The Story AI responded: "Once upon a time there was an old man who loved to play. He had lots of fun playing with his toys and he would always remember how much it was. One day, the old man decided to take him out for some help. He took off his toy car and started walking around the park until he saw something strange in the sky! It looked like a big, shiny rock that made him feel safe from himself as he wanted to keep it safe. The ancient man smiled at himself: "I'm sure you can use this special power". So they went on their way home together in front of them..." (the rest seems to have been cut off.)
Apart from sounding utterly insane, it worked, and the Elevenlabs read all of that.
Thanks again!

**Comment by TheComamba** [comment]
Nice, thank you!

An Api key is an idea I also had. Maybe one day. 🙂
