### ISSUE TITLE
Add the option to contact a server per API key

### ISSUE THREAD

**Issue by TheComamba** [TheComamba/UnKenny#30]

**Comment by KingphilAusti** [comment]
Basic support is added. 
Points to work out:
- How to deal with API-Key security 
- Design of actor configuration

**Comment by KingphilAusti** [comment]
It might also be interesting to handle the previous conversation back to the network. Up to a maximum of n converstation steps.

Like:
```            
{ 
  { role: 'system', content: await actor.getFlag("unkenny", "preamble"), },  
  { role: 'user', content: <message m-n>,}
  { role: 'assistant', content: <response m-n>,}
  ...
  { role: 'user', content: <message m-1>,}
  { role: 'assistant', content: <response m-1>,}
  { role: 'user', content: input,}
}
```

**Comment by TheComamba** [comment]
I created issue #31 to track passing previous messages.

**Comment by KingphilAusti** [comment]
Had to merge #29 since I needed some of the logic. 

What options do we want to add? Quite different from to the local models. Hier is a selection for OpenAI. https://platform.openai.com/docs/api-reference/chat/create
