### ISSUE TITLE
Can we avoid having to post messages ourselves?

### ISSUE THREAD

**Issue by TheComamba** [TheComamba/UnKenny#64]
This would be much preferable to the hack we currently use.

There is the ChatMessageRender hook.

One issue is that the text is scanned for chat commands, and our /alias command clashes with that.

So maybe we do the text replacement in ChatMessage, and trigger calculating the response in ChatMessageRender.

How do we know if the text contained an unkenny command?

Maybe we need to rethink if we really want to use the /alias Syntax. We _are_ about to release breaking changes, so now would be the time to do that.

**Comment by TheComamba** [comment]
I want to remove the chat command feature for the following reasons:
* The input text is not recognised as valid input by FoundryVTT. That means that we have to intervene and replace stuff quite early on.
* Because of this, we have to use a hack and post the message in the chat ourselves.
* It is not seen from the posted text that this addresses an unkenny actor. The @-Syntax on the other hand is very straightforward.

**Comment by TheComamba** [comment]
Hjep, getting more complicated again. To post a message, we need to call the processMessage function on ChatLog. For that, we need to get the ChatLog. And as this function only takes the message as argument, setting the speaker will be a small challenge. Maybe we can work with a hook.

**Comment by KingphilAusti** [comment]
Kinda hacky but works now. In triggerResponse now creates a `new ChatLog().processMessage("#TeamEmilia" + JSON.stringify(chatData))`, where chatData encodes response + message type + actor name. `#TeamEmilia` is used as a stop word for triggering logic in our overridden version of `ChatMessage._preCreate`.
