### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by Daitsuke** [TheComamba/UnKenny#85]
Hello,

I am currently trying to install this module; however, I get this error message.
Would you please advise what it is that I am not doing correctly or is there something that I am overlooking?
![image](https://github.com/TheComamba/UnKenny/assets/45607975/99734a3e-6825-4c71-b20c-f3defb1eb768)

Thank you in advance.

**Comment by TheComamba** [comment]
At first glance this looks very much like us doing something wrong. I will look into this tomorrow.

**Comment by KingphilAusti** [comment]
Updating a previous installation works fine. New installs not. 
Links on foundry webpage also only point to newest version now: https://foundryvtt.com/packages/unkenny/
Seems to be a linking problem. Testing links in a browser works. 
We are on it.

**Comment by TheComamba** [comment]
I linked the github webview of the module.json instead of the raw data. This explains why Foundry coudn't parse it. I fixed that in the release script, and I took the opportunity to add some more consistency checks. I hope to release v1.0.2 soon, after I checked my changes.

**Comment by TheComamba** [comment]
I released a patched version, the installation now works for me.
Thanks for reaching out to us, @Daitsuke. :)
